// Generated by Wrangler by running `wrangler types ./worker/worker-configuration.d.ts`

interface Env {
	ASSETS: Fetcher;
	MIDDLECACHE: R2Bucket;
	ANTHROPIC_API_KEY: string;
}
declare module "*/__redirects" {
	const value: string;
	export default value;
}
